version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

volumes:
  mongodata:
