version: '3.8'

services:
  backend:
    image: docker.io/extim/links-shortener-backend:arm64-latest
    env_file:
      - ./backend/.env.prod
    depends_on:
      - mongo
    # ports:
    #   - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    environment:
      - APP_ENV=production
      - RUST_LOG=backend=info,actix_web=info
      - SERVICE_NAME=url-shortener
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-api.tls=true"
      - "traefik.http.routers.backend-api.entrypoints=websecure"
      - "traefik.http.routers.backend-api.rule=Host(`api.links.extim.su`)"
      - "traefik.http.services.backend-api-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend-api.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.backend-api.tls.options=intermediate@file"
      - "traefik.http.routers.backend-api.middlewares=default@file"
    network_mode: bridge
    links:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: docker.io/extim/links-shortener-frontend:arm64-latest
    # ports:
    #   - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-links.tls=true"
      - "traefik.http.routers.frontend-links.entrypoints=websecure"
      - "traefik.http.routers.frontend-links.rule=Host(`links.extim.su`)"
      - "traefik.http.services.frontend-links-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.frontend-links.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.frontend-links.tls.options=intermediate@file"
      - "traefik.http.routers.frontend-links.middlewares=default@file"
    network_mode: bridge
    links:
      - backend

  mongo:
    image: mongo:7
    # ports:
    #   - "27017:27017"
    volumes:
      - ./mongodata:/data/db
    restart: unless-stopped
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

