name: Build Docker Images (ARM64, GHCR)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ${{ github.repository }}/links-shortener-backend
  IMAGE_FRONTEND: ${{ github.repository }}/links-shortener-frontend

jobs:
  # build-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GHCR_TOKEN }}

  #     - name: Build and push backend image (arm64)
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./backend
  #         file: ./backend/Dockerfile
  #         platforms: linux/arm64
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}/links-shortener-backend:arm64-latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push frontend image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/links-shortener-frontend:arm64-latest
